### ISSUE TITLE
chmod: ./rr: No such file or directory

### ISSUE THREAD

**Issue by necrogami** [spiral/ticket-booking#13]
When trying to run this example, i run run.sh i get ./rr does not exist during the compile

when docker starts,

web
cinema
payment
users
centrifugo-rpc

all those containers just repeat: `chmod: ./rr: No such file or directory`

**Comment by necrogami** [comment]
Also if i uncomment the get-binary line and also run that in the shared folder i receive this in the shared folder.

```shell
╰─ﬀ ./rr compile
unknown command "compile" for "rr"
```

**Comment by butschster** [comment]
fixed
